export const rtKeys = {
  int32Add: 'runtime.int32.add',
  int32Subtract: 'runtime.int32.subtract',
  int32Multiply: 'runtime.int32.multiply',
  int32Divide: 'runtime.int32.divide',
  int32Modulo: 'runtime.int32.modulo',
  int32Negate: 'runtime.int32.negate',
  int32Absolute: 'runtime.int32.absolute',
  int32Odd: 'runtime.int32.odd',
  int32And: 'runtime.int32.and',
  int32Or: 'runtime.int32.or',
  int32Not: 'runtime.int32.not',

  float32Add: 'runtime.float32.add',
  float32Subtract: 'runtime.float32.subtract',
  float32Multiply: 'runtime.float32.multiply',
  float32Divide: 'runtime.float32.divide',
  float32Negate: 'runtime.float32.negate',
  float32Absolute: 'runtime.float32.absolute',
  float32SquareRoot: 'runtime.float32.squareRoot',
  float32Sine: 'runtime.float32.sine',
  float32Cosine: 'runtime.float32.cosine',
  float32Exponential: 'runtime.float32.exponential',
  float32Logarithm: 'runtime.float32.logarithm',
  float32Arctangent: 'runtime.float32.arctangent',

  booleanAnd: 'runtime.boolean.and',
  booleanOr: 'runtime.boolean.or',
  booleanNot: 'runtime.boolean.not',

  compareEqual: 'runtime.compare.equal',
  compareNotEqual: 'runtime.compare.notEqual',
  compareLess: 'runtime.compare.less',
  compareLessOrEqual: 'runtime.compare.lessOrEqual',
  compareGreater: 'runtime.compare.greater',
  compareGreaterOrEqual: 'runtime.compare.greaterOrEqual',

  bitmapUnion: 'runtime.bitmap.union',
  bitmapIntersection: 'runtime.bitmap.intersection',
  bitmapDifference: 'runtime.bitmap.difference',
  bitmapEqual: 'runtime.bitmap.equal',
  bitmapNotEqual: 'runtime.bitmap.notEqual',
  bitmapSubset: 'runtime.bitmap.subset',
  bitmapSuperset: 'runtime.bitmap.superset',
  bitmapContains: 'runtime.bitmap.contains',
  bitmapRange: 'runtime.bitmap.range',
  bitmapSingleton: 'runtime.bitmap.singleton',

  castCharToInt32: 'runtime.cast.char.to.int32',
  castBooleanToInt32: 'runtime.cast.boolean.to.int32',
  castInt32ToChar: 'runtime.cast.int32.to.char',
  castFloat32ToInt32: 'runtime.cast.float32.to.int32',
  castFloat32ToInt32Round: 'runtime.cast.float32.to.int32.round',

  pointerDereference: 'runtime.pointer.dereference',
  pointerAssign: 'runtime.pointer.assign',
  pointerDisposeCheck: 'runtime.pointer.disposeCheck',

  hookFunctionEnter: 'runtime.debug.hook.function.enter',

  debugRangeCheck: 'runtime.debug.range.check',
  debugStepsCheck: 'runtime.debug.steps.check',
  debugDivideCheck: 'runtime.debug.divide.check',
  debugModuloCheck: 'runtime.debug.modulo.check',
  debugAssertView: 'runtime.debug.assert.view',

  fileReset: 'runtime.file.reset',
  fileRewrite: 'runtime.file.rewrite',
  fileGet: 'runtime.file.get',
  filePeek: 'runtime.file.peek',
  filePut: 'runtime.file.put',
  filePutBufferBlock: 'runtime.file.put.buffer.block',
  filePutBufferByte: 'runtime.file.put.buffer.byte',
  filePutBufferCharacter: 'runtime.file.put.buffer.character',
  filePutBufferText: 'runtime.file.put.buffer.text',
  fileReadCharacter: 'runtime.file.read.character',
  fileReadToken: 'runtime.file.read.token',
  fileWriteText: 'runtime.file.write.text',
  fileWriteByte: 'runtime.file.write.byte',
  fileWriteBytes: 'runtime.file.write.bytes',
  fileWriteBlock: 'runtime.file.write.block',
  fileReadln: 'runtime.file.readln',
  fileWriteln: 'runtime.file.writeln',
  fileEof: 'runtime.file.eof',
  fileEoln: 'runtime.file.eoln',
  filePage: 'runtime.file.page',
  fileCreate: 'runtime.file.create',
  fileProgramUrl: 'runtime.file.program.url',

  convertInt32ToText: 'runtime.convert.int32.to.text',
  convertInt32ToBytes: 'runtime.convert.int32.to.bytes',
  convertInt32ToChar: 'runtime.convert.int32.to.char',
  convertBytesToTextField: 'runtime.convert.bytes.to.text.field',
  convertFloat32ToText: 'runtime.convert.float32.to.text',
  convertFloat32ToBytes: 'runtime.convert.float32.to.bytes',
  convertBooleanToText: 'runtime.convert.boolean.to.text',
  convertBooleanToBytes: 'runtime.convert.boolean.to.bytes',
  convertTextToInt32: 'runtime.convert.text.to.int32',
  convertTextToFloat32: 'runtime.convert.text.to.float32',
  convertTextToBoolean: 'runtime.convert.text.to.boolean',
  convertBytesToInt32: 'runtime.convert.bytes.to.int32',
  convertBytesToFloat32: 'runtime.convert.bytes.to.float32',
  convertBytesToBoolean: 'runtime.convert.bytes.to.boolean',
  convertCharToInt32: 'runtime.convert.char.to.int32',

  bytesHost: 'runtime.bytes.host',
  bytesAlloc: 'runtime.bytes.alloc',
  bytesCopy: 'runtime.bytes.copy',
  bytesClone: 'runtime.bytes.clone',
  viewSubarray: 'runtime.view.subarray',

  bytesGetInt8: 'runtime.bytes.get.int8',
  bytesGetUint8: 'runtime.bytes.get.uint8',
  bytesGetInt16: 'runtime.bytes.get.int16',
  bytesGetUint16: 'runtime.bytes.get.uint16',
  bytesGetInt32: 'runtime.bytes.get.int32',
  bytesGetFloat32: 'runtime.bytes.get.float32',
  bytesSetInt8: 'runtime.bytes.set.int8',
  bytesSetUint8: 'runtime.bytes.set.uint8',
  bytesSetInt16: 'runtime.bytes.set.int16',
  bytesSetUint16: 'runtime.bytes.set.uint16',
  bytesSetInt32: 'runtime.bytes.set.int32',
  bytesSetFloat32: 'runtime.bytes.set.float32',

  objectArrayGet: 'runtime.objectarray.get',
  objectArraySet: 'runtime.objectarray.set',
  objectArraySublist: 'runtime.objectarray.sublist',
  bytesPack: 'runtime.bytes.pack',
  bytesUnpack: 'runtime.bytes.unpack',

  objectGet: 'runtime.object.get',
  objectSet: 'runtime.object.set',

  objectNew: 'runtime.object.new',
  objectClone: 'runtime.object.clone',
  objectArrayNew: 'runtime.objectarray.new',
  objectArrayClone: 'runtime.objectarray.clone',

  assign: 'runtime.assign',

  closureNoValue: 'runtime.closure.noValue',

  cellNew: 'runtime.cell.new',
  cellGet: 'runtime.cell.get',
  cellSet: 'runtime.cell.set',

  callIndirect: 'runtime.call.indirect',
} as const
